"""Add price to Garment

Revision ID: 53b3a62e3140
Revises: 6ce4df75fcba
Create Date: 2026-08-09 17:13:05.352118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b3a62e3140'
down_revision: Union[str, Sequence[str], None] = '6ce4df75fcba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garments', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garments', 'price')
    # ### end Alembic commands ###
