"""Add thumbnail

Revision ID: 90854e37b3a0
Revises: 085c34e6d40f
Create Date: 2026-08-09 20:19:02.894278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90854e37b3a0'
down_revision: Union[str, Sequence[str], None] = '085c34e6d40f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garment_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
        batch_op.alter_column('ai_generated_image_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garment_assets', schema=None) as batch_op:
        batch_op.alter_column('ai_generated_image_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
